### ISSUE TITLE
GitHub training

### ISSUE THREAD

**Issue by kritkondru** [kritkondru/CS6392018#1]

**Comment by ankijaws** [comment]
I am Ankita Jawale and I tested the app of Kritin Kondru .
The Min and Target versions of the SDKs are 23 and 27. 
I tested the app on a phone and emulator with OS 6.0 Marshmallow. 
The app does not crash.
The app does display:
Hello Kritin Kondru
And
Welcome in CS 639 Summer 2018

The name of the student is displayed.

I find your work up to mark and as per requirement.
A slight change you can do is instead of using Constraint Layout, use Linear Layout as parent layout and use gravity for textView inorder to align the textview at center. This will just reduce the number of lines in your xml part.
